# name: SonarCloud
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     #types: [opened, synchronize, reopened] # Mahaveer : Remove this line as  not using this
#     types: [closed] # Mahaveer : If the pull request is closed trigger the workflow 

#https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved
on:
  pull_request_review:
    types: [submitted]
  push:
    branches: [ main ]   
jobs:
  build:
    if: github.event.review.state == 'approved'
    name: Dependency Check Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports