name: "Main / Pull Pipeline "
on:
    pull_request:
        # paths-ignore:
        #     - '.txt'
        #     - 'LICENSE'
        #     - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main
jobs:
  # Run SnarQube Analysis
  sast_sonar_scan:
    uses: ./.github/workflows/build.yml

  # Run Credential Check
  password_check:
    uses: ./.github/workflows/dependency-check.yml

  # Run Dependencies Check
  depenencies_check:
    uses: ./.github/workflows/password-check.yml