name: Docker Vulnerability Scan

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on:
    workflow_call:

# Mahaveer https://github.com/aquasecurity/trivy-action

jobs:
  vulnerability-scan:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build -t ${{github.repository}}:${{ github.sha }} .

      - name: Install Trivy  #https://github.com/aquasecurity/trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.45.0/trivy_0.45.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.45.0_Linux-64bit.deb

      #  Scan the Docker image for vulnerabilities
      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL  ${{github.repository}}:${{ github.sha }}

      # Upload the Trivy report as an artifact
      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: ./trivy-report.txt
