name: Docker Vulnerability Scan

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on:
    workflow_call:

# Mahaveer https://github.com/aquasecurity/trivy-action

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-docker-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-docker-results.sarif'
