#on: [push]
name: Password and Sensitive Information Check
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-checker:
    runs-on: ubuntu-latest
    name: Vulnerabilities check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
      - name: Check for vulnerabilities
        id: checks
        uses: maddygoround/secretduty@v1.4
      - name: Get results of scan
        run: |
          echo "Scan Results - ${{ steps.checks.outputs.result }}" | tee -a ${{github.workspace}}/reports/report.txt"

      - name: Upload Password Test results
        uses: actions/upload-artifact@master
        with:
          name: Password Cred report
          path: ${{github.workspace}}/reports